version: 0.2

phases:
  pre_build:
    commands:
      - cd client
      - npm install -g next
      - npm install
  build:
    commands:
      - npm run build
      - npm run export

artifacts:
  files:
    - "**/*"
  base-directory: client/dist
